In [ ]:
#Anomly(abnormality) in my dataset
'''
1.High Null Value
2.Missing columns
3.Outliers
4.Categorical:
    Gender-->MALE,FEMALE,OTHER
'''

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv("/config/workspace/artifact/12282022__130709/data_ingestion/dataset/train.csv")

In [6]:
df

,class,aa_000,ab_000,ac_000,ad_000,ae_000,af_000,ag_000,ag_001,ag_002,...,ee_002,ee_003,ee_004,ee_005,ee_006,ee_007,ee_008,ee_009,ef_000,eg_000
0,neg,22,2.0,4.400000e+01,NaN,0.0,0.0,0.0,0.0,3454.0,...,196.0,34.0,46.0,24.0,10.0,0.0,0.0,0.0,0.0,0.0
1,neg,10,NaN,0.000000e+00,0.0,0.0,0.0,0.0,0.0,0.0,...,36.0,26.0,36.0,46.0,100.0,26.0,0.0,0.0,0.0,0.0
2,neg,41474,NaN,5.980000e+02,NaN,0.0,0.0,0.0,0.0,0.0,...,331610.0,177770.0,348412.0,315844.0,237834.0,148534.0,258180.0,15748.0,0.0,0.0
3,neg,18928,NaN,1.406000e+03,1406.0,0.0,0.0,0.0,0.0,0.0,...,58134.0,5134.0,1764.0,92.0,14.0,0.0,0.0,0.0,0.0,0.0
4,neg,26,NaN,2.000000e+01,20.0,0.0,0.0,0.0,0.0,0.0,...,508.0,76.0,72.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28945,neg,180262,NaN,0.000000e+00,NaN,0.0,0.0,0.0,0.0,0.0,...,1519772.0,988792.0,3290222.0,1440160.0,588876.0,259714.0,385322.0,31364.0,0.0,0.0
28946,neg,39754,NaN,4.900000e+02,466.0,0.0,0.0,0.0,0.0,0.0,...,181658.0,96452.0,270364.0,344880.0,382150.0,238500.0,192166.0,1652.0,0.0,0.0
28947,neg,1798,NaN,4.400000e+01,36.0,0.0,0.0,0.0,0.0,0.0,...,9082.0,6750.0,16788.0,12258.0,10300.0,8948.0,14866.0,140.0,0.0,0.0
28948,neg,179692,0.0,2.130706e+09,704.0,18.0,34.0,0.0,0.0,0.0,...,486262.0,254052.0,394340.0,308248.0,926104.0,1086352.0,18538.0,0.0,0.0,0.0
28949,neg,30766,NaN,5.260000e+02,506.0,0.0,0.0,0.0,0.0,0.0,...,181734.0,88012.0,194604.0,396336.0,181866.0,113420.0,166686.0,17838.0,0.0,0.0

In [16]:
null_report = df.isnull().sum()/df.shape[0]

In [17]:
null_report[null_report>0.3]

ab_000    0.772297
bk_000    0.379206
bl_000    0.447703
bm_000    0.652746
bn_000    0.725250
bo_000    0.762383
bp_000    0.785009
bq_000    0.802073
br_000    0.810743
cr_000    0.772297
dtype: float64

In [14]:
drop_column_names = []
for column_name , missing_percentage in zip((df.isnull().sum()/df.shape[0]).index , (df.isnull().sum()/df.shape[0]).values):
    print(column_name,missing_percentage)
    if missing_percentage>0.3:
        drop_column_names.append(column_name)

class 0.0
aa_000 0.0
ab_000 0.7722970639032816
ac_000 0.05951640759930915
ad_000 0.2560621761658031
ae_000 0.044317789291882556
af_000 0.044317789291882556
ag_000 0.010535405872193437
ag_001 0.010535405872193437
ag_002 0.010535405872193437
ag_003 0.010535405872193437
ag_004 0.010535405872193437
ag_005 0.010535405872193437
ag_006 0.010535405872193437
ag_007 0.010535405872193437
ag_008 0.010535405872193437
ag_009 0.010535405872193437
ah_000 0.010984455958549223
ai_000 0.0107426597582038
aj_000 0.0107426597582038
ak_000 0.07844559585492228
al_000 0.010880829015544042
am_0 0.0107426597582038
an_000 0.010880829015544042
ao_000 0.009740932642487047
ap_000 0.010880829015544042
aq_000 0.009740932642487047
ar_000 0.04825561312607945
as_000 0.0107426597582038
at_000 0.0107426597582038
au_000 0.0107426597582038
av_000 0.04435233160621762
ax_000 0.04435233160621762
ay_000 0.010535405872193437
ay_001 0.010535405872193437
ay_002 0.010535405872193437
ay_003 0.010535405872193437
ay_004 0.010535405872193437
ay_005 0.010535405872193437
ay_006 0.010535405872193437
ay_007 0.010535405872193437
ay_008 0.010535405872193437
ay_009 0.010535405872193437
az_000 0.010535405872193437
az_001 0.010535405872193437
az_002 0.010535405872193437
az_003 0.010535405872193437
az_004 0.010535405872193437
az_005 0.010535405872193437
az_006 0.010535405872193437
az_007 0.010535405872193437
az_008 0.010535405872193437
az_009 0.010535405872193437
ba_000 0.0107426597582038
ba_001 0.0107426597582038
ba_002 0.0107426597582038
ba_003 0.0107426597582038
ba_004 0.0107426597582038
ba_005 0.0107426597582038
ba_006 0.0107426597582038
ba_007 0.0107426597582038
ba_008 0.0107426597582038
ba_009 0.0107426597582038
bb_000 0.010984455958549223
bc_000 0.048290155440414505
bd_000 0.048290155440414505
be_000 0.044386873920552676
bf_000 0.044317789291882556
bg_000 0.010880829015544042
bh_000 0.010880829015544042
bi_000 0.009740932642487047
bj_000 0.009740932642487047
bk_000 0.3792055267702936
bl_000 0.44770293609671846
bm_000 0.6527461139896373
bn_000 0.7252504317789292
bo_000 0.7623834196891192
bp_000 0.7850086355785838
bq_000 0.8020725388601037
br_000 0.8107426597582038
bs_000 0.011778929188255613
bt_000 0.0021416234887737477
bu_000 0.011433506044905008
bv_000 0.011433506044905008
bx_000 0.05291882556131261
by_000 0.007461139896373057
bz_000 0.04825561312607945
ca_000 0.07751295336787564
cb_000 0.011778929188255613
cc_000 0.05288428324697755
cd_000 0.011329879101899828
ce_000 0.04442141623488774
cf_000 0.2560621761658031
cg_000 0.2560621761658031
ch_000 0.2560621761658031
ci_000 0.005595854922279792
cj_000 0.005595854922279792
ck_000 0.005595854922279792
cl_000 0.1614853195164076
cm_000 0.16732297063903281
cn_000 0.01070811744386874
cn_001 0.01070811744386874
cn_002 0.01070811744386874
cn_003 0.01070811744386874
cn_004 0.01070811744386874
cn_005 0.01070811744386874
cn_006 0.01070811744386874
cn_007 0.01070811744386874
cn_008 0.01070811744386874
cn_009 0.01070811744386874
co_000 0.2560621761658031
cp_000 0.048290155440414505
cq_000 0.011433506044905008
cr_000 0.7722970639032816
cs_000 0.010500863557858377
cs_001 0.010500863557858377
cs_002 0.010500863557858377
cs_003 0.010500863557858377
cs_004 0.010500863557858377
cs_005 0.010500863557858377
cs_006 0.010500863557858377
cs_007 0.010500863557858377
cs_008 0.010500863557858377
cs_009 0.010500863557858377
ct_000 0.2376511226252159
cu_000 0.2376511226252159
cv_000 0.2376511226252159
cx_000 0.2376511226252159
cy_000 0.2376511226252159
cz_000 0.2376511226252159
da_000 0.2376511226252159
db_000 0.2376511226252159
dc_000 0.2376511226252159
dd_000 0.04442141623488774
de_000 0.048290155440414505
df_000 0.07115716753022452
dg_000 0.07119170984455958
dh_000 0.07119170984455958
di_000 0.07112262521588947
dj_000 0.07115716753022452
dk_000 0.07115716753022452
dl_000 0.07119170984455958
dm_000 0.07122625215889465
dn_000 0.011433506044905008
do_000 0.04825561312607945
dp_000 0.04832469775474957
dq_000 0.04832469775474957
dr_000 0.048290155440414505
ds_000 0.04832469775474957
dt_000 0.04832469775474957
du_000 0.048290155440414505
dv_000 0.048290155440414505
dx_000 0.04825561312607945
dy_000 0.048290155440414505
dz_000 0.04825561312607945
ea_000 0.04825561312607945
eb_000 0.07115716753022452
ec_00 0.17385146804835924
ed_000 0.1614853195164076
ee_000 0.010535405872193437
ee_001 0.010535405872193437
ee_002 0.010535405872193437
ee_003 0.010535405872193437
ee_004 0.010535405872193437
ee_005 0.010535405872193437
ee_006 0.010535405872193437
ee_007 0.010535405872193437
ee_008 0.010535405872193437
ee_009 0.010535405872193437
ef_000 0.048290155440414505
eg_000 0.04825561312607945

In [15]:
drop_column_names

['ab_000',
 'bk_000',
 'bl_000',
 'bm_000',
 'bn_000',
 'bo_000',
 'bp_000',
 'bq_000',
 'br_000',
 'cr_000']

In [6]:
(df.isnull().sum()/df.shape[0]).index

Index(['class', 'aa_000', 'ab_000', 'ac_000', 'ad_000', 'ae_000', 'af_000',
       'ag_000', 'ag_001', 'ag_002',
       ...
       'ee_002', 'ee_003', 'ee_004', 'ee_005', 'ee_006', 'ee_007', 'ee_008',
       'ee_009', 'ef_000', 'eg_000'],
      dtype='object', length=171)

In [1]:
from glob import glob

In [2]:
glob("/config/workspace/saved_model/1")

['/config/workspace/saved_model/1']

In [4]:
from sensor.predictor import ModelResolver

In [5]:
model_resolver = ModelResolver()

In [7]:
model_resolver.get_latest_save_model_path()

'saved_models/0/model/model.pkl'